### ISSUE TITLE
Change README filename

### ISSUE THREAD

**Issue by mahchiahui** [Senzing/aws-cloudformation-ecs#22]
**Is your feature request related to a problem? Please describe.**
Develop a cloudformation script with api gateway and cognito. Write down the steps to authenticate to the api gateway.

**Comment by docktermj** [comment]
Potential issue with AWS API Gateway:   A 29 second timeout.

References:

- https://stackoverflow.com/questions/31973388/amazon-api-gateway-timeout
- https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#http-api-quotas
- https://forums.aws.amazon.com/thread.jspa?threadID=248560

**Comment by docktermj** [comment]
@mahchiahui I'm going to close this.
