### ISSUE TITLE
Improve performance of sending messages to SQS

### ISSUE THREAD

**Issue by docktermj** [Senzing/aws-cloudformation-ecs#63]
Currently there looks like a 750 KBps limit of sending messages to SQS.   Investigate how to send data to SQS faster.

This seems to be related to the following "players":

1. The file on S3 accessed via HTTPS
1. stream-producer.py
1. boto3 python library
1. AWS ECS networking
1. AWS SQS

**Comment by roncewind** [comment]
PR merged
